project_id = "FutBeat"

[functions.futbeat-api]
verify_jwt = false

[functions.futbeat-live-sync]
verify_jwt = true

[functions.futbeat-push-dispatch]
verify_jwt = true

[functions.futbeat-country-sync]
verify_jwt = true

[functions.futbeat-fixtures-sync]
verify_jwt = true

[functions.futbeat-goal-live-sync]
verify_jwt = false
